### ISSUE TITLE
ImportError: no module named 'polysynth'

### ISSUE THREAD

**Issue by THREELabs** [transistortester/thumby-polysynth#2]
Beginning of my file I have:
#from sys import path as syspath
#syspath.insert(0, '/Games/MyGame')

And imported with:
import polysynth

Confirmed polysynth.py file exists in the MyGame folder.

For some reason I am getting:
ImportError: no module named 'polysynth'

I must be:
Not importing the file correctly and the import is not seeing the file. Thoughts?

**Comment by transistortester** [comment]
Are the first two lines are commented out in the file? If so, try removing the `#` at the start of them.

**Comment by THREELabs** [comment]
Hey there thanks for quick response, was just temporary had it disabled for now.  This is the setup at the moment
![example](https://github.com/transistortester/thumby-polysynth/assets/51836729/460aa345-0f44-470a-8292-ff2a447213fe)

**Comment by transistortester** [comment]
Does the error happen on real hardware too, or just the emulator? It's possible that the checkbox to include it in emulation isn't selected.
Would also be good to double check the path of the opened `polysynth.py` window to make sure it matches the one on the thumby. I assume it already does, but it wouldn't hurt to check.
Also curious, did you shift some things around after the error happened? Noticed that the error's line number doesn't match.

**Comment by THREELabs** [comment]
I'll look this over a bit more. I didn't actually test on the hardware so I will consider that. Regarding the error on the line number was most likely from shifting things around. I'll close this for now and will revisit after I review some more. Thanks!

**Comment by THREELabs** [comment]
I wanted to chime back in on this. I resolved this.  I noticed on the instructions it stated to add this:
from sys import path as syspath
syspath.insert(0, "/Games/(your game folder)")


I used the PSDemo as an example, and noticed the code on that was:
from sys import path as syspath
syspath.append("/Games/(your game folder)") #fix imports

**Comment by transistortester** [comment]
Both `syspath.insert(0, path)` and `syspath.append(path)` will work, the only difference is which file will be prioritized for import if you have multiple in different locations with the same name. Using `syspath.insert(0, path)` will _always_ prefer files the game folder, whereas `syspath.append(path)` will prefer the root of the storage and the `/lib` folder.
In general, `syspath.insert(0, path)` is probably better since having an incompatible version of a file in a different folder doesn't risk unexpectedly breaking a game.
I suspect that PSdemo using `syspath.append(path)` is just a holdover from earlier projects, which I didn't change when I wrote the docs.

**Comment by THREELabs** [comment]
Got it, thanks for the detailed description!
