### ISSUE TITLE
Question about using polysynth with thumby.audio.play

### ISSUE THREAD

**Issue by THREELabs** [transistortester/thumby-polysynth#3]
If polysynth is playing some music first, I noticed after that the game doesn't play audio like:
        thumby.audio.playBlocking(300, 250)
        thumby.audio.play(260, 250)

Do I need to use one or the other for handling audio or revisit my code thanks!

**Comment by transistortester** [comment]
Correct, you can only use one or the other. Polysynth needs to take full control of the audio output to work.
It's easy to swap for polysynth functions as an alternative, though needing a duration makes things a bit more complicated.
You can use the following as a direct replacement for `thumby.audio.playBlocking`:
```python
polysynth.setpitch(channel, pitch)
time.sleep_ms(duration)
polysynth.setpitch(channel, None)
```
The closest equivalent there is to `thumby.audio.play` is the following:
```python
polysynth.playnote(channel, note, ins=polysynth.instrument(length=duration))
```
Though this uses note numbering instead of measuring pitch in Hertz.
It would also be possible to use a stream, or simply `polysynth.setpitch(channel, pitch)` and remember to turn the channel off later, which is basically what `thumby.audio.play` does under the hood anyway.
I may add in a drop-in replacement at some point in the future just to make this easier.

**Comment by THREELabs** [comment]
Thank you!
